### ISSUE TITLE
Add ```update``` to prm command

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-tools#18]
We should be able to string together prm commands in one call.

```
prm --prefix=$pre --start=2002-09 --stop=2003-10 --merge-dss(=flow|all)  build run update
--check-dates=fail | replace | merge   # Default =fail
--items=                   # Default = all
--(no-)metadata='Metadata Note`      # Default = --metadata=''
--merge-dss(=flow|all)  # --merge-dss is same as --merge-dss=all
```

For --merge-flow, the file `$pre.[DSS|dss]` is also read, and merged into the results.  This happens as follows:
- Every FLOW-DIV(KAF) item is read, and converted to JSON,
- It is compared to the current data in the flow.csv file
- If they are the same, then continue
- If they are different, then compare the time-range.  
  -  If they match, then update the data.  
- If they don't match, then 
  - If  `check-dates=fail`, skip this update, alert the user
  - If  `check-dates=replace`, replace the data with the newly supplied data
  - If `check-dates=merge`, report not-implemented and skip update.
- If any changes have been made to the file, and --metadata is active (default) add an entry to the README.md file.  If there is a `# Changes` section, add it to the top, if there isn't , then create one at end of file. 

``````
## Quinn Hart <qjhart@ucdavis.edu> {flow:1}  2015-01-23 12:35:15
Metadata Note
```prm --prefix=$pre --start=2002-09 --stop=2003-10 --merge-dss(=flow|all)  build run update``` 
``````

**Comment by jrmerz** [comment]
@qjhart split out 'string commands' to issue #20

**Comment by jrmerz** [comment]
@qjhart I can't get a proper build.  Can you send me example output files to test the 'update' command?

**Comment by jrmerz** [comment]
@qjhart the java class TimeSeriesContainer easily dumps to JSON using the Jackson library.  In keeping with the strategy of trying to do as little as possible in the Java code/Runtime, am going to have a runtime command that takes a dss file location and dumps each record into a tmp folder as it's own .json file.  The will be a lookup index.json file as well.  The nodejs prm code can just read the tmp .json files and make required modifications from there.

Thoughts?

**Comment by jrmerz** [comment]
FYI, pulling data out of the DSS file is, well, not fast.

**Comment by jrmerz** [comment]
I have uploaded Runtime v1.4 which include the file export.  Running:

```
prm update-library && prm init
```

Should update the nodejs code and download the latest runtime.  The _prm update_ command is not complete yet, it just generates the json files at the moment in a local folder.  I am proposing (and have already added but can change) the following flags for _prm update_
- **--cache**: Keeps the dssExportJson_[prefix] directory after creating json files.  If this directory already exists, no dss to json extract is preformed on **prm update**.
- **--clean-cache**: Keeps the dssExportJson_[prefix] directory after creating json files but always extracts dss to json file, removing folder if it exists.
- **--regex**: Defaults to '.*FLOW_LOC.*'.  Regular expression match for paths in DSS file to extract.  This saves a LOT of time, only extracting what you need, flow extract time is ~2.5min.  This match is against the entire DSS path.

Also of note, I have redone how the Runtimes child processes interacts with the nodejs/prm process. If the **--verbose** flag is passed, stdout and stderr are now streamed to the console instead of a bulk dump when the process exits.  stderr is colored red in the console.
