### ISSUE TITLE
Calibration Node Inclusion in Matrix

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-tools#44]
@jdherman @msdogan 

I am in the process of migrating to the new HOBBES format.  I will be implementing this CNF tool so PRMNAMEs will be still used, so there will be no changes to the matrix file.  That said, I have stumbled on this issue with Calibration nodes.  

Basically in the old HOBBES crawler, if a node did not have a geometry, it was ignored.  Of the 5 CN nodes only CN2 had a geometry, so it is the only calibration node showing in the Matrix file.  There is one link from this CN.

```
CN2.2002-01-31,SINK.2002-01-31,0,0,1,0,1000000000
CN2.2002-02-28,SINK.2002-02-28,0,0,1,0,1000000000
INFLOW.2002-01-31,CN2.2002-01-31,0,0,1,10000,10000
INFLOW.2002-02-28,CN2.2002-02-28,0,0,1,10000,10000
CN2.2002-01-31,N201.2002-01-31,0,0,1,0,0
CN2.2002-02-28,N201.2002-02-28,0,0,1,0,0
```

My question, is this correct?  Seems like the CN's should be all or none... no?

**Comment by jdherman** [comment]
Speaking only for myself, I'm not sure what the calibration nodes are used for ...

My gut reaction is the same as yours Justin, it should be all or nothing. This looks like it might have been a temporary experiment.

**Comment by msdogan** [comment]
Okay maybe I should first describe why we have those CN1 .. CN5 nodes. Those Calibration Nodes represent magical flows to make the model feasible. Before Karan and I updated the model, those magical calibration flows were all over the place. We removed all of them. Then I created 5 nodes for each region and called CN to distinguish from other inflows because these are magical. However, after Karan and I updated the model, there was one node N201 for which we couldn't eliminate debug flows. So, I created a magic inflow and it's used only two or three times in the whole 82 year period and the amount is really small. So, it doesn't change results but it makes the model feasible. So, I created 5 nodes in Microsoft Access database but only CN2 was connected to the CALVIN network, so that's why we don't see CN1, CN3, CN4, and CN5 in HOBBES database. Above links seem right for CN2, probably, for that period calibration flows to N201 is zero. When we have it, it is constrained flow, just like other inflows.

If you want to represent in a different way to make it consistent, we can do that. I am open to any other suggestion :)

**Comment by jdherman** [comment]
Ok I think I understand. So this would be the next step AFTER running debug mode and saying "at this point in the network there isn't enough water..." so then you would add these magic nodes where you could inject a small amount of extra water into the system.

In that case yea I guess we'd have to keep it.

**Comment by msdogan** [comment]
yes @jdherman

**Comment by jrmerz** [comment]
Ok, this is all fine with me, I think my issue is a developer/design one.  Current the HOBBES parser ignores all CN nodes except CN2 simply because the other CN's do not have geometry associated with them.  I don't think this is very intuitive (or good design).  I'm going to propose (and will move forward with unless I hear objections) adding a 'disabled' flag to nodes, links.  Then the CALVIN tools will check this flag and only nodes specifically set to disabled=true will be omitted from the matrix.

Again, let me know if you have objections to this.  Otherwise I am going to try and move forward with the transition this morning.  Will let you know when all is complete.

**Comment by msdogan** [comment]
sounds good to me

**Comment by jrmerz** [comment]
Added disabled flag.
